@PaymentService_HostAddress = http://localhost:8082

POST {{PaymentService_HostAddress}}/api/payments
Content-Type: application/json

{
  "clientId": "client-123",
  "amount": 49.99,
  "currency": "USD",
  "description": "Book purchase"
}

###

GET {{PaymentService_HostAddress}}/api/payments
Accept: application/json

###
